# 🌾 CropIQ — Crop Recommendation System

A full-stack machine learning web application that recommends the best crop to grow based on soil and climate conditions. All trained models predict **simultaneously** and results are displayed side-by-side with confidence scores, top-3 probabilities, and a majority vote consensus.

---

## 🖥️ Demo

> Enter 7 soil & climate parameters → All models predict at once → See consensus recommendation + individual model cards

---

## 🧠 ML Models Used

| Model | Accuracy |
|---|---|
| XGBoost | ~99.3% |
| Random Forest | ~99.5% |
| Decision Tree | ~98.0% |
| Naive Bayes | ~99.5% |
| Logistic Regression | ~97.3% |

Trained on the **Crop Recommendation Dataset** — 2,200 samples, 22 crop classes, 7 features.

---

## 🗂️ Project Structure

```
ML project/
├── venv/                        ← Python virtual environment
├── requirements.txt             ← Python dependencies
│
├── models/                      ← Trained .pkl files (generated by notebook)
│   ├── scaler.pkl
│   ├── label_encoder.pkl
│   ├── metrics.json
│   ├── xgboost.pkl
│   ├── naive_bayes.pkl
│   ├── decision_tree.pkl
│   ├── logistic_regression.pkl
│   └── random_forest.pkl
│
├── train_models.ipynb           ← Jupyter notebook: EDA + training
│
├── backend/                     ← Django REST API (MVC)
│   ├── manage.py
│   ├── backend/
│   │   ├── settings.py          ← Config: CORS, DRF, ML_MODELS_DIR
│   │   └── urls.py              ← Root URL router
│   └── crop_api/
│       ├── ml_model.py          ← MODEL: loads .pkl files, runs predictions
│       ├── serializers.py       ← Input validation
│       ├── views.py             ← CONTROLLER: HTTP → model → JSON response
│       └── urls.py              ← API routes
│
└── frontend/                    ← React + Vite + Tailwind CSS
    └── src/
        ├── services/
        │   └── api.js           ← All axios HTTP calls
        ├── components/
        │   ├── InputForm.jsx    ← 7-parameter slider form
        │   ├── ModelCard.jsx    ← Per-model prediction card
        │   ├── ConsensusCard.jsx← Majority vote banner
        │   └── ComparisonChart.jsx ← Recharts bar chart + metrics table
        └── App.jsx              ← Root component
```

---

## ⚙️ Tech Stack

**ML & Data**
- Python, Jupyter Notebook
- scikit-learn, XGBoost
- pandas, numpy, matplotlib, seaborn
- joblib (model serialization)

**Backend**
- Django 6.x
- Django REST Framework
- django-cors-headers

**Frontend**
- React 18 + Vite
- Tailwind CSS v4
- Recharts
- Axios

---

## 🚀 Getting Started

### Prerequisites
- Python 3.10+
- Node.js 18+
- Git

---

### Step 1 — Clone & set up virtual environment

```bash
git clone <your-repo-url>
cd "ML project"

# Create and activate venv
python -m venv venv

# Windows
venv\Scripts\activate

# Mac/Linux
source venv/bin/activate

# Install Python dependencies
pip install -r requirements.txt
```

---

### Step 2 — Train the models

Open `train_models.ipynb` in Jupyter and run all cells:

```bash
jupyter notebook
```

This creates all `.pkl` files inside the `models/` folder. Only needs to be done **once**.

---

### Step 3 — Start the Django backend

```bash
cd backend
python manage.py migrate      # first time only
python manage.py runserver    # starts on http://127.0.0.1:8000
```

Verify it's working:
```
GET http://127.0.0.1:8000/api/health/
```
Expected: `{ "status": "ok", "models_loaded": 4 }`

---

### Step 4 — Start the React frontend

Open a **new terminal** (keep Django running):

```bash
cd frontend
npm install       # first time only
npm run dev       # starts on http://localhost:5173
```

Open **http://localhost:5173** in your browser.

---

## 📡 API Endpoints

| Method | Endpoint | Description |
|--------|----------|-------------|
| `POST` | `/api/predict/` | Run all models and return predictions |
| `GET` | `/api/metrics/` | Training metrics for all models |
| `GET` | `/api/crops/` | All 22 possible crop labels |
| `GET` | `/api/health/` | Server health check |

### POST `/api/predict/` — Request body

```json
{
    "N": 90,
    "P": 42,
    "K": 43,
    "temperature": 20.8,
    "humidity": 82.0,
    "ph": 6.5,
    "rainfall": 202.9
}
```

### Response

```json
{
    "majority_vote": "rice",
    "vote_count": 4,
    "total_models": 4,
    "results": [
        {
            "name": "XGBoost",
            "slug": "xgboost",
            "prediction": "rice",
            "confidence": 99.87,
            "top3": [
                { "crop": "rice",   "prob": 99.87 },
                { "crop": "jute",   "prob": 0.04  },
                { "crop": "coffee", "prob": 0.01  }
            ],
            "accuracy": 99.32,
            "precision": 99.35,
            "recall": 99.32,
            "f1": 99.31,
            "train_time": 0.829
        }
    ]
}
```

---

## 🌱 Input Parameters

| Parameter | Description | Range |
|-----------|-------------|-------|
| N | Nitrogen content in soil | 0 – 140 mg/kg |
| P | Phosphorus content in soil | 5 – 145 mg/kg |
| K | Potassium content in soil | 5 – 205 mg/kg |
| temperature | Temperature | 0 – 50 °C |
| humidity | Relative humidity | 0 – 100 % |
| ph | Soil pH level | 0 – 14 |
| rainfall | Rainfall | 0 – 300 mm |

---

## 🌾 Supported Crops (22)

Rice, Maize, Chickpea, Kidney Beans, Pigeon Peas, Moth Beans, Mung Bean,
Black Gram, Lentil, Pomegranate, Banana, Mango, Grapes, Watermelon,
Muskmelon, Apple, Orange, Papaya, Coconut, Cotton, Jute, Coffee

---

## 🏗️ Architecture — MVC Pattern

```
React (View)
    ↓  POST /api/predict/  (JSON)
Django Views (Controller)
    ↓  calls predict_all()
ml_model.py (Model)
    ↓  loads .pkl → runs inference
    ↑  returns results list
Django Views
    ↑  JSON response
React (View)
    ↑  renders ModelCards + ConsensusCard
```

---

## 📦 requirements.txt

```
django
djangorestframework
django-cors-headers
scikit-learn
xgboost
joblib
numpy
pandas
notebook
matplotlib
seaborn
```

Generate fresh with:
```bash
pip freeze > requirements.txt
```

---

## 👤 Author

**Sanket Sunil Nagathan**
- Email: sanketnagathan@gmail.com
- LinkedIn: [sanket-sunil-nagathan](https://www.linkedin.com/in/sanket-sunil-nagathan/)

---

## 📄 License

This project is open source and available under the [MIT License](LICENSE).